/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigzhao_jianrmagicbox_CppInterface */

#ifndef _Included_com_bigzhao_jianrmagicbox_CppInterface
#define _Included_com_bigzhao_jianrmagicbox_CppInterface
//#ifdef __cplusplus
//extern "C" {
//#endif
	/*
	* Class:     com_bigzhao_jianrmagicbox_CppInterface
	* Method:    init
	* Signature: ()V
	*/
extern "C" JNIEXPORT void JNICALL Java_com_bigzhao_jianrmagicbox_CppInterface_init(JNIEnv *, jclass);

	/*
	* Class:     com_bigzhao_jianrmagicbox_CppInterface
	* Method:    nativeAction
	* Signature: (I[Ljava/lang/String;)Ljava/lang/Object;
	*/
extern "C" JNIEXPORT jobject JNICALL Java_com_bigzhao_jianrmagicbox_CppInterface_nativeAction(JNIEnv *, jclass, jint, jobjectArray);

//#ifdef __cplusplus
//}
//#endif
#endif
